name: "Build plugin linux-glibc-x86_64"

on:
  workflow_dispatch:

jobs:
  build-linux:
    name: Build Linux
    runs-on: ubuntu-22.04

    permissions:
      contents: write # IMPORTANT: mandatory for making GitHub Releases

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: automake autoconf libtool libtool-bin build-essential nasm yasm cmake python3 python3-pip python3-dev
          version: 1.0

      - name: Build plugins
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          cd ~
          gh release list -L 100000 --repo '${{ github.repository }}' | grep -m1 "compiler-*" | cut -f3 | xargs -i gh release download {} --repo '${{ github.repository }}' --pattern 'crosstool-ng-compiler-linux-x86_64*'
          tar xzf crosstool-ng-compiler-linux-x86_64.tar.gz
          export PATH="${HOME}/x-tools/x86_64-unknown-linux-gnu/bin:$PATH"
          pip3 install meson ninja pyzstd click
          cd ${{ github.workspace }}
          gh release list -L 100000 --repo '${{ github.repository }}' | grep -m1 "vapoursynth-*" | cut -f3 | xargs -i gh release download {} --repo '${{ github.repository }}' --pattern 'vapoursynth-build-linux-x86_64*'
          tar xzf vapoursynth-build-linux-x86_64.tar.gz
          export PYTHONPATH=${{ github.workspace }}/workspace/lib/python3.10/site-packages
          ./github-build.py '${{ github.repository }}'

      - name: Upload log
        uses: actions/upload-artifact@v4
        with:
          name: buildlog-linux-glibc-x86_64
          path: ${{ github.workspace }}/build.log
          if-no-files-found: error
