name: "Build plugin win64"

on:
  workflow_dispatch:

jobs:
  build-win64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >-
            base-devel
            zip
            mingw-w64-ucrt-x86_64-jq
            mingw-w64-ucrt-x86_64-gcc
            mingw-w64-ucrt-x86_64-pkg-config
            mingw-w64-ucrt-x86_64-vapoursynth
            mingw-w64-ucrt-x86_64-meson
            mingw-w64-ucrt-x86_64-ninja
            mingw-w64-ucrt-x86_64-cmake
            mingw-w64-ucrt-x86_64-autotools
            mingw-w64-ucrt-x86_64-nasm
            mingw-w64-ucrt-x86_64-yasm
            mingw-w64-ucrt-x86_64-python-pip
            mingw-w64-ucrt-x86_64-zstd

      - name: Build plugins
        run: |
          cd '${{ github.workspace }}'
          python -m pip install pyzstd
          python github-build.py '${{ github.repository }}'

      - name: Upload log
        uses: actions/upload-artifact@v4
        with:
          name: buildlog-win64
          path: ${{ github.workspace }}/build.log
          if-no-files-found: error
